// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/entries-:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/entries-[id].delete').default>>>>
    }
    '/api/entries': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/entries.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/entries.post').default>>>>
    }
    '/uploads-:name': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/uploads-[name].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}